### PR TITLE
Remove decorators from message_handler.py

### PR DESCRIPTION
**Pull request by Otto-AA**
Following the suggestions from #14 I've removed the decorators.

Not 100% happy with the logging, as it is really overstuffed this way. Will probably make a `log_args` method (e.g. `def log_args(self, *, title, args, keys)`) to make it clearer.

### CODE REVIEW

**Review by johan-bjareholt — APPROVED** [review]
Much better IMO.

Also, as you can see there's 35 additions and 96 deletions with the same functionality.

**Comment by Otto-AA** [comment]
What do you think about the parser declarations, @johan-bjareholt ?
I am torn between declaring them at the top of the file (as it is now) and declaring them inside the specific functions. The first one has the advantage, that the functions are a bit shorter, the second one excels in (1) having no bulk of parser declarations at the top and (2) to let the developer know which additional arguments are parsed. I currently tend to move them into the functions.

**Comment by johan-bjareholt** [comment]
Regarding the parser declarations I actually don't really think it matters much, both options seem fine.

**Comment by Otto-AA** [comment]
Ok, then I'll leave it as it is

**Pull request merged**
